[package]
name = "v8-api"
version = "0.1.0"
edition = "2024"

[dependencies]
deno_core = "0.382.0"
tiny-skia = "0.11" 
font-kit="*"
tokio = { version = "1", features = ["full"] }
glutin = "0.32.3"
anyhow = "1.0"
base64 = "0.21"